ASP.NET_Core/MVC/03_CompanySite/Site/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Site.Models; 

public class LoginViewModel {

    [Required]
    [Display(Name = "Login")]
    public string? UserName { get; set; }

    [Required]
    [UIHint("password")]
    [Display(Name = "Пароль")]
    public string? Password { get; set; }

    [Display(Name = "Запомнить меня?")]
    public bool RememberMe { get; set; }
}

ASP.NET_Core/MVC/03_CompanySite/Site/Models/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Site.Domain;

namespace Site.Models.ViewComponents;

public class SidebarViewComponent : ViewComponent {
    private readonly DataManager dataManager;

    public SidebarViewComponent(DataManager dataManager) {
        this.dataManager = dataManager;
    }

    public Task<IViewComponentResult> InvokeAsync() {
        return Task.FromResult((IViewComponentResult)View("Default", dataManager.ServiceItems.GetServiceItems()));
    }
}

ASP.NET_Core/MVC/03_CompanySite/Site/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Site.Domain;

namespace Site.Areas.Admin.Controllers; 

[Area("Admin")]
public class HomeController : Controller {

    private readonly DataManager _dataManager;
    public HomeController(DataManager dataManager) => _dataManager = dataManager;
    
    public IActionResult Index() {
        return View(_dataManager.ServiceItems.GetServiceItems());
    }
}

ASP.NET_Core/MVC/03_CompanySite/Site/Areas/Admin/Controllers/ServiceItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Site.Domain;
using Site.Domain.Entities;
using Site.Service;

namespace Site.Areas.Admin.Controllers;

[Area("Admin")]
public class ServiceItemsController : Controller {
    private readonly DataManager dataManager;
    private readonly IWebHostEnvironment hostingEnvironment;
    public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment) {
        this.dataManager = dataManager;
        this.hostingEnvironment = hostingEnvironment;
    }

    public IActionResult Edit(Guid id) {
        var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
        return View(entity);
    }

    [HttpPost]
    public IActionResult Edit(ServiceItem model, IFormFile titleImageFile) {
        if (ModelState.IsValid) {
            if (titleImageFile != null) {
                model.TitleImagePath = titleImageFile.FileName;
                using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create)) {
                    titleImageFile.CopyTo(stream);
                }
            }
            dataManager.ServiceItems.SaveServiceItem(model);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
        return View(model);
    }

    [HttpPost]
    public IActionResult Delete(Guid id) {
        dataManager.ServiceItems.DeleteServiceItem(id);
        return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
    }
}

ASP.NET_Core/MVC/03_CompanySite/Site/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using Site.Domain.Entities;
using Site.Domain;
using Site.Service;

namespace Site.Areas.Admin.Controllers; 

[Area("Admin")]
public class TextFieldsController : Controller {

    private readonly DataManager dataManager;
    public TextFieldsController(DataManager dataManager) {
        this.dataManager = dataManager;
    }

    public IActionResult Edit(string codeWord) {
        var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
        return View(entity);
    }

    [HttpPost]
    public IActionResult Edit(TextField model) {
        if (ModelState.IsValid) {
            dataManager.TextFields.SaveTextField(model);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
        return View(model);
    }
}

ASP.NET_Core/MVC/03_CompanySite/Site/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Site.Models;

namespace Site.Controllers; 

[Authorize]
public class AccountController : Controller {
    private readonly UserManager<IdentityUser> userManager;
    private readonly SignInManager<IdentityUser> signInManager;
    public AccountController(UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signinMgr) {
        userManager = userMgr;
        signInManager = signinMgr;
    }

    [AllowAnonymous]
    public IActionResult Login(string returnUrl) {
        ViewBag.returnUrl = returnUrl;
        return View(new LoginViewModel());
    }

    [HttpPost]
    [AllowAnonymous]
    public async Task<IActionResult> Login(LoginViewModel model, string returnUrl) {
        if (ModelState.IsValid) {
            IdentityUser? user = await userManager.FindByNameAsync(model.UserName);
            if (user != null) {
                await signInManager.SignOutAsync();
                Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                if (result.Succeeded) {
                    return Redirect(returnUrl ?? "/");
                }
            }
            ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
        }
        return View(model);
    }

    [Authorize]
    public async Task<IActionResult> Logout() {
        await signInManager.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }
}

ASP.NET_Core/MVC/03_CompanySite/Site/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Site.Domain;

namespace Site.Controllers;

public class HomeController : Controller {
	private readonly DataManager dataManager;

	public HomeController(DataManager dataManager) {
		this.dataManager = dataManager;
	}

	public IActionResult Index() {
		return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
	}

	public IActionResult Contacts() {
		return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
	}
}

ASP.NET_Core/MVC/03_CompanySite/Site/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using Site.Domain;

namespace Site.Controllers;

public class ServicesController : Controller {
    private readonly DataManager dataManager;

    public ServicesController(DataManager dataManager) {
        this.dataManager = dataManager;
    }

    public IActionResult Index(Guid id) {
        if (id != default) {
            return View("Show", dataManager.ServiceItems.GetServiceItemById(id));
        }

        ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageServices");
        return View(dataManager.ServiceItems.GetServiceItems());
    }
}

ASP.NET_Core/MVC/03_CompanySite/Site/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Наши услуги</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услуги</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

ASP.NET_Core/MVC/03_CompanySite/Site/Views/Shared/Components/Sidebar/Default.cshtml
@model IQueryable<ServiceItem>

@if (Model?.Any() == true) {
    <section>
        <h2>Наши услуги</h2>
        <ul class="small-image-list">
            @foreach (ServiceItem entity in Model) {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>
                        @entity.Title
                    </h4>
                    <p>
                        @entity.Subtitle
                    </p>
                </li>
            }
        </ul>
    </section>
}